### ISSUE TITLE
Incorrect EXPECTED value in wait_for_steward function

### ISSUE THREAD

**Issue by chelios** [projectsyn/try.syn.tools#2]
I was working through the "Getting Started with Project Syn" introduction and the steward setup step 

``` shell 
curl -fsL https://try.syn.tools/steward | bash
```
kept getting stuck in a loop. 

After downloading and reviewing the script it seems that the EXPECTED value in the `wait_for_steward` function was set incorrectly.

Changing it from
```shell
EXPECTED="True True True True True"
```
to 
```shell
to EXPECTED="True"
```

appeared to fix the issue.

**Comment by simu** [comment]
Hey, thanks for the report!

I just checked the script, and the current value of `EXPECTED="True True True True True"` matches the expected state of 5 running pods after a successful Steward installation. We expect 5 running pods, since Steward will create an initial ArgoCD which consists of 4 additional pods (redis, argocd-server, argocd-repo-server and argocd-application-controller).

**Comment by chelios** [comment]
OK, that's interesting. Mine never got to that stage, even after about 30 minutes.

I will retry and come back to you if I cannot get it to work as expected.
